apiVersion: v1
kind: Pod
metadata: 
  name: user-api
  labels:
    app: myapp
spec:
  containers:
    - name: user-api
      image: vamsikrishnadell/user-api
      ports:
       - containerPort: 8080
