apiVersion: v1
kind: Pod
metadata: 
  name: go-user-api
  labels:
    app: myapp
spec:
  containers:
    - name: go-user-api
      image: vamsisiddu/go-user-api:v1
      ports:
       - containerPort: 8080
